name: Default

on: 
  push:
  schedule: 
    - cron: "0 2 * * 0-6"
  status:


jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_11.2.1.app
      # Note: Mapping of Xcode version to Swift version can be found here: https://swift.org/download/#releases
      # Note: Xcode locations can be found here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015
      
    - name: Check Swift Version
      run: swift --version

    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
