name: Swift

on: 
  push:
  pull_request:
  schedule: 
    - cron: "0 2 * * 0-6"


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
